language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - "npm install gitbook-cli -g"

before_deploy:
  - "gitbook build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master